### PR TITLE
Add license documentation

### PR DESCRIPTION
**Pull request by RaphaelAudet**

### CODE REVIEW

**Comment by RaphaelAudet** [comment]
this PR resolves #11

**Comment by carlos-salinas** [comment]
LGMT

**Comment by carlos-salinas** [comment]
After I merged to master, I missed a comment above the lines regarding the license, in the Dockerfile. Could you please add it?

**Comment by RaphaelAudet** [comment]
Could you comment the line you are talking about in the diff of this pull request  (even if it is merge, so I can know precisely the nature of your comment for a future commit) ?

**Pull request merged**
